version: '3'

services:

  # cloak-server:
  #   build: ../../cloak
  #   restart: unless-stopped
  #   command: ["-s", "54.178.117.120", "-p", "443"]
  #   volumes:
  #     - ./ckclient.json:/etc/cloak/ckclient.json:ro
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "100m"
  #       max-file: "7"

  v2fly-server:
    build: ../../v2fly
    restart: unless-stopped
    ports:
      - "3129:3128"
      - "1081:1080"
    volumes:
      - ./v2fly-config.jsonc:/etc/v2ray/config.jsonc:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "7"
