version: '3'

services:

  v2fly-server:
    build: ../../v2fly
    restart: unless-stopped
    volumes:
      - ./v2fly-config.jsonc:/etc/v2ray/config.jsonc:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "7"


  cloak-server:
    build: ../../cloak
    restart: unless-stopped
    entrypoint: [ "ck-server", "-c", "/etc/cloak/ckserver.json" ]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ckserver.json:/etc/cloak/ckserver.json:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "7"
