name: Build and Push

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      cloak_version:
        description: 'Cloak Version'
        required: false
        type: string
    
env:
  CLOAK_VERSION: ${{ inputs.cloak_version || vars.CLOAK_VERSION }}

permissions:
  contents: read
  packages: write

jobs:

  Release:
    name: Release
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v7
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v4
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      # - 
      #   name: Login to DockerHub
      #   uses: docker/login-action@v4
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v7
        with:
          push: true
          set: |
            cloak.args.CLOAK_VERSION=${{ env.CLOAK_VERSION }}
